### ISSUE TITLE
Update of elm-css to latest version

### ISSUE THREAD

**Issue by kraklin** [ken-matsui/html-styled-extra#2]
Hey @ken-matsui 

We started to use `elm-css` and we are used to `Html.Extra` so we naturally wanted to use your package. But we can't because of it's incompatibility with current version of `elm-css`.

I see it is updated in the master branch but it is not released. Do you plan to release it soon or should we fork the library and do it ourselves?

**Comment by ken-matsui** [comment]
Hi @kraklin 
Thanks for letting me know. I've published 1.0.2 [here](https://package.elm-lang.org/packages/matken11235/html-styled-extra/1.0.2/) :)

**Comment by ken-matsui** [comment]
Hey @kraklin 
I'd just give you a heads up for package name changes.
I've updated this package name from `matken11235/html-styled-extra` to `ken-matsui/html-styled-extra`.
This change caused the version reversion to 1.0.0, but I will maintain it instead of the old one.
Thus, I'd recommend making sure to switch it in case of keeping this package up-to-date.

**Comment by kraklin** [comment]
Great, good to know. Thanks for the heads up and keep up the great work in Elm ;)
